# ACID RADIO - Developed by acidvegas in Python (https://git.supernets.org/acidvegas/acid-radio)
# acid-radio/radio.acid.vegas.conf

server {
    if ($block_ua) { return 444; }

    listen      443 ssl http2;
    listen [::]:443 ssl http2;

    server_name radio.acid.vegas;

    location / {
        proxy_pass http://127.0.0.1:7000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_request_buffering off;
    }

    ssl_certificate     /etc/letsencrypt/live/radio.acid.vegas/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/radio.acid.vegas/privkey.pem;
}

server {
    if ($block_ua) { return 444; }

    listen      80;
    listen [::]:80;

    if ($host = radio.acid.vegas) {
        return 301 https://$host$request_uri;
    }

    server_name radio.acid.vegas;

    return 404;
}